#pragma once

#include "../../pch.h"
#include "../../Common/CommonStructs.h"

using namespace System;
using namespace System::Runtime::InteropServices;
using namespace System::Runtime::CompilerServices;
using namespace System::Collections::Generic;
using namespace System::Collections::ObjectModel;
using namespace msclr;
using namespace msclr::interop;
using namespace DirectXNet::Common;

#define MESSAGE_ID(name) name ## = D3D12_MESSAGE_ID_ ## name

namespace DirectXNet
{
    namespace DirectX12
    {
        namespace Debug
        {
            /// <summary>
            /// Flags for optional D3D12 Debug Layer features.
            /// </summary>
            [Flags]
            public enum class D3D12DebugFeature : UINT
            {
                /// <summary>
                /// The default. No optional Debug Layer features.
                /// </summary>
                None = D3D12_DEBUG_FEATURE_NONE,

                /// <summary>
                /// The Debug Layer is allowed to deliberately change functional behavior of an
                /// application in order to help identify potential errors. By default, the Debug Layer
                /// allows most invalid API usage to run the natural course.
                /// </summary>
                AllowBehaviorChangingDebugAids = D3D12_DEBUG_FEATURE_ALLOW_BEHAVIOR_CHANGING_DEBUG_AIDS,

                /// <summary>
                /// Performs additional resource state validation of resources set in descriptors at the
                /// time D3D12CommandQueue::ExecuteCommandLists is called. By design descriptors can be
                /// changed even after submitting command lists assuming proper synchronization.
                /// Conservative resource state tracking ignores this allowance and validates all resources
                /// used in descriptor tables when ExecuteCommandLists is called. The result may be false
                /// validation errors.
                /// </summary>
                ConservativeResourceStateTracking = D3D12_DEBUG_FEATURE_CONSERVATIVE_RESOURCE_STATE_TRACKING,

                /// <summary>
                /// Disables validation of bundle commands by virtually injecting checks into the calling
                /// command list validation paths.
                /// </summary>
                DisableVirtualizedBundlesValidation = D3D12_DEBUG_FEATURE_DISABLE_VIRTUALIZED_BUNDLES_VALIDATION,

                EmulateWindows7 = D3D12_DEBUG_FEATURE_EMULATE_WINDOWS7
            };

            /// <summary>
            /// Specifies options for the amount of information to report about a live device object's
            /// lifetime.
            /// </summary>
            [Flags]
            public enum class D3D12RLDOFlags : UINT
            {
                None = D3D12_RLDO_NONE,

                /// <summary>
                /// Obtain a summary about a live device object's lifetime.
                /// </summary>
                Summary = D3D12_RLDO_SUMMARY,

                /// <summary>
                /// Obtain detailed information about a live device object's lifetime.
                /// </summary>
                Detail = D3D12_RLDO_DETAIL,

                /// <summary>
                /// This flag indicates to ignore objects which have no external refcounts keeping them
                /// alive. D3D objects are printed using an external refcount and an internal refcount.
                /// Typically, all objects are printed. This flag means ignore the objects whose external
                /// refcount is 0, because the application is not responsible for keeping them alive.
                /// </summary>
                IgnoreInternal = D3D12_RLDO_IGNORE_INTERNAL
            };

            /// <summary>
            /// Specifies categories of debug messages. This will identify the category of a message when
            /// retrieving a message with D3D12InfoQueue::GetMessage and when adding a message with
            /// D3D12InfoQueue::AddMessage. When creating an info queue filter, these values can be used
            /// to allow or deny any categories of messages to pass through the storage and retrieval
            /// filters.
            /// </summary>
            public enum class D3D12MessageCategory : UINT
            {
                /// <summary>
                /// Indicates a user defined message.
                /// </summary>
                ApplicationDefined = ::D3D12_MESSAGE_CATEGORY_APPLICATION_DEFINED,

                /// <summary>
                /// Miscellaneous category.
                /// </summary>
                Miscellaneous = ::D3D12_MESSAGE_CATEGORY_MISCELLANEOUS,

                /// <summary>
                /// Initialization category.
                /// </summary>
                Initialization = ::D3D12_MESSAGE_CATEGORY_INITIALIZATION,

                /// <summary>
                /// Cleanup category.
                /// </summary>
                Cleanup = ::D3D12_MESSAGE_CATEGORY_CLEANUP,

                /// <summary>
                /// Compilation category.
                /// </summary>
                Compilation = ::D3D12_MESSAGE_CATEGORY_COMPILATION,

                /// <summary>
                /// State creation category.
                /// </summary>
                StateCreation = ::D3D12_MESSAGE_CATEGORY_STATE_CREATION,

                /// <summary>
                /// State setting category.
                /// </summary>
                StateSetting = ::D3D12_MESSAGE_CATEGORY_STATE_SETTING,

                /// <summary>
                /// State getting category.
                /// </summary>
                StateGetting = ::D3D12_MESSAGE_CATEGORY_STATE_GETTING,

                /// <summary>
                /// Resource manipulation category.
                /// </summary>
                ResourceManipulation = ::D3D12_MESSAGE_CATEGORY_RESOURCE_MANIPULATION,

                /// <summary>
                /// Execution category.
                /// </summary>
                Execution = ::D3D12_MESSAGE_CATEGORY_EXECUTION,

                /// <summary>
                /// Shader category.
                /// </summary>
                Shader = ::D3D12_MESSAGE_CATEGORY_SHADER
            };

            /// <summary>
            /// Debug message severity levels for an information queue.
            /// </summary>
            public enum class D3D12MessageSeverity : UINT
            {
                /// <summary>
                /// Defines some type of corruption that has occurred.
                /// </summary>
                Corruption = ::D3D12_MESSAGE_SEVERITY_CORRUPTION,

                /// <summary>
                /// Defines an error message.
                /// </summary>
                Error = ::D3D12_MESSAGE_SEVERITY_ERROR,

                /// <summary>
                /// Defines a warning message.
                /// </summary>
                Warning = ::D3D12_MESSAGE_SEVERITY_WARNING,

                /// <summary>
                /// Defines an information message.
                /// </summary>
                Info = ::D3D12_MESSAGE_SEVERITY_INFO,

                /// <summary>
                /// Defines a message other than corruption, error, warning, or information.
                /// </summary>
                Message = ::D3D12_MESSAGE_SEVERITY_MESSAGE
            };

            /// <summary>
            /// Specifies debug message IDs for setting up an info-queue filter; use these messages to
            /// allow or deny message categories to pass through the storage and retrieval filters. These
            /// IDs are used by methods such as D3D12InfoQueue::GetMessage or D3D12InfoQueue::AddMessage.
            /// </summary>
            public enum class D3D12MessageID
            {
                MESSAGE_ID(UNKNOWN),
                MESSAGE_ID(STRING_FROM_APPLICATION),
                MESSAGE_ID(CORRUPTED_THIS),
                MESSAGE_ID(CORRUPTED_PARAMETER1),
                MESSAGE_ID(CORRUPTED_PARAMETER2),
                MESSAGE_ID(CORRUPTED_PARAMETER3),
                MESSAGE_ID(CORRUPTED_PARAMETER4),
                MESSAGE_ID(CORRUPTED_PARAMETER5),
                MESSAGE_ID(CORRUPTED_PARAMETER6),
                MESSAGE_ID(CORRUPTED_PARAMETER7),
                MESSAGE_ID(CORRUPTED_PARAMETER8),
                MESSAGE_ID(CORRUPTED_PARAMETER9),
                MESSAGE_ID(CORRUPTED_PARAMETER10),
                MESSAGE_ID(CORRUPTED_PARAMETER11),
                MESSAGE_ID(CORRUPTED_PARAMETER12),
                MESSAGE_ID(CORRUPTED_PARAMETER13),
                MESSAGE_ID(CORRUPTED_PARAMETER14),
                MESSAGE_ID(CORRUPTED_PARAMETER15),
                MESSAGE_ID(CORRUPTED_MULTITHREADING),
                MESSAGE_ID(MESSAGE_REPORTING_OUTOFMEMORY),
                MESSAGE_ID(GETPRIVATEDATA_MOREDATA),
                MESSAGE_ID(SETPRIVATEDATA_INVALIDFREEDATA),
                MESSAGE_ID(SETPRIVATEDATA_CHANGINGPARAMS),
                MESSAGE_ID(SETPRIVATEDATA_OUTOFMEMORY),
                MESSAGE_ID(CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT),
                MESSAGE_ID(CREATESHADERRESOURCEVIEW_INVALIDDESC),
                MESSAGE_ID(CREATESHADERRESOURCEVIEW_INVALIDFORMAT),
                MESSAGE_ID(CREATESHADERRESOURCEVIEW_INVALIDVIDEOPLANESLICE),
                MESSAGE_ID(CREATESHADERRESOURCEVIEW_INVALIDPLANESLICE),
                MESSAGE_ID(CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS),
                MESSAGE_ID(CREATESHADERRESOURCEVIEW_INVALIDRESOURCE),
                MESSAGE_ID(CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT),
                MESSAGE_ID(CREATERENDERTARGETVIEW_UNSUPPORTEDFORMAT),
                MESSAGE_ID(CREATERENDERTARGETVIEW_INVALIDDESC),
                MESSAGE_ID(CREATERENDERTARGETVIEW_INVALIDFORMAT),
                MESSAGE_ID(CREATERENDERTARGETVIEW_INVALIDVIDEOPLANESLICE),
                MESSAGE_ID(CREATERENDERTARGETVIEW_INVALIDPLANESLICE),
                MESSAGE_ID(CREATERENDERTARGETVIEW_INVALIDDIMENSIONS),
                MESSAGE_ID(CREATERENDERTARGETVIEW_INVALIDRESOURCE),
                MESSAGE_ID(CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT),
                MESSAGE_ID(CREATEDEPTHSTENCILVIEW_INVALIDDESC),
                MESSAGE_ID(CREATEDEPTHSTENCILVIEW_INVALIDFORMAT),
                MESSAGE_ID(CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS),
                MESSAGE_ID(CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE),
                MESSAGE_ID(CREATEINPUTLAYOUT_OUTOFMEMORY),
                MESSAGE_ID(CREATEINPUTLAYOUT_TOOMANYELEMENTS),
                MESSAGE_ID(CREATEINPUTLAYOUT_INVALIDFORMAT),
                MESSAGE_ID(CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT),
                MESSAGE_ID(CREATEINPUTLAYOUT_INVALIDSLOT),
                MESSAGE_ID(CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS),
                MESSAGE_ID(CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH),
                MESSAGE_ID(CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE),
                MESSAGE_ID(CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE),
                MESSAGE_ID(CREATEINPUTLAYOUT_INVALIDALIGNMENT),
                MESSAGE_ID(CREATEINPUTLAYOUT_DUPLICATESEMANTIC),
                MESSAGE_ID(CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE),
                MESSAGE_ID(CREATEINPUTLAYOUT_NULLSEMANTIC),
                MESSAGE_ID(CREATEINPUTLAYOUT_MISSINGELEMENT),
                MESSAGE_ID(CREATEVERTEXSHADER_OUTOFMEMORY),
                MESSAGE_ID(CREATEVERTEXSHADER_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATEVERTEXSHADER_INVALIDSHADERTYPE),
                MESSAGE_ID(CREATEGEOMETRYSHADER_OUTOFMEMORY),
                MESSAGE_ID(CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATEGEOMETRYSHADER_INVALIDSHADERTYPE),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE),
                MESSAGE_ID(CREATEPIXELSHADER_OUTOFMEMORY),
                MESSAGE_ID(CREATEPIXELSHADER_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATEPIXELSHADER_INVALIDSHADERTYPE),
                MESSAGE_ID(CREATERASTERIZERSTATE_INVALIDFILLMODE),
                MESSAGE_ID(CREATERASTERIZERSTATE_INVALIDCULLMODE),
                MESSAGE_ID(CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP),
                MESSAGE_ID(CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC),
                MESSAGE_ID(CREATEBLENDSTATE_INVALIDSRCBLEND),
                MESSAGE_ID(CREATEBLENDSTATE_INVALIDDESTBLEND),
                MESSAGE_ID(CREATEBLENDSTATE_INVALIDBLENDOP),
                MESSAGE_ID(CREATEBLENDSTATE_INVALIDSRCBLENDALPHA),
                MESSAGE_ID(CREATEBLENDSTATE_INVALIDDESTBLENDALPHA),
                MESSAGE_ID(CREATEBLENDSTATE_INVALIDBLENDOPALPHA),
                MESSAGE_ID(CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK),
                MESSAGE_ID(CLEARDEPTHSTENCILVIEW_INVALID),
                MESSAGE_ID(COMMAND_LIST_DRAW_ROOT_SIGNATURE_NOT_SET),
                MESSAGE_ID(COMMAND_LIST_DRAW_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(COMMAND_LIST_DRAW_VERTEX_BUFFER_NOT_SET),
                MESSAGE_ID(COMMAND_LIST_DRAW_VERTEX_BUFFER_STRIDE_TOO_SMALL),
                MESSAGE_ID(COMMAND_LIST_DRAW_VERTEX_BUFFER_TOO_SMALL),
                MESSAGE_ID(COMMAND_LIST_DRAW_INDEX_BUFFER_NOT_SET),
                MESSAGE_ID(COMMAND_LIST_DRAW_INDEX_BUFFER_FORMAT_INVALID),
                MESSAGE_ID(COMMAND_LIST_DRAW_INDEX_BUFFER_TOO_SMALL),
                MESSAGE_ID(COMMAND_LIST_DRAW_INVALID_PRIMITIVETOPOLOGY),
                MESSAGE_ID(COMMAND_LIST_DRAW_VERTEX_STRIDE_UNALIGNED),
                MESSAGE_ID(COMMAND_LIST_DRAW_INDEX_OFFSET_UNALIGNED),
                MESSAGE_ID(DEVICE_REMOVAL_PROCESS_AT_FAULT),
                MESSAGE_ID(DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT),
                MESSAGE_ID(DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT),
                MESSAGE_ID(CREATEINPUTLAYOUT_TRAILING_DIGIT_IN_SEMANTIC),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_TRAILING_DIGIT_IN_SEMANTIC),
                MESSAGE_ID(CREATEINPUTLAYOUT_TYPE_MISMATCH),
                MESSAGE_ID(CREATEINPUTLAYOUT_EMPTY_LAYOUT),
                MESSAGE_ID(LIVE_OBJECT_SUMMARY),
                MESSAGE_ID(LIVE_DEVICE),
                MESSAGE_ID(LIVE_SWAPCHAIN),
                MESSAGE_ID(CREATEDEPTHSTENCILVIEW_INVALIDFLAGS),
                MESSAGE_ID(CREATEVERTEXSHADER_INVALIDCLASSLINKAGE),
                MESSAGE_ID(CREATEGEOMETRYSHADER_INVALIDCLASSLINKAGE),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTREAMTORASTERIZER),
                MESSAGE_ID(CREATEPIXELSHADER_INVALIDCLASSLINKAGE),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTREAM),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDENTRIES),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDSTRIDES),
                MESSAGE_ID(CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMSTRIDES),
                MESSAGE_ID(CREATEHULLSHADER_OUTOFMEMORY),
                MESSAGE_ID(CREATEHULLSHADER_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATEHULLSHADER_INVALIDSHADERTYPE),
                MESSAGE_ID(CREATEHULLSHADER_INVALIDCLASSLINKAGE),
                MESSAGE_ID(CREATEDOMAINSHADER_OUTOFMEMORY),
                MESSAGE_ID(CREATEDOMAINSHADER_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATEDOMAINSHADER_INVALIDSHADERTYPE),
                MESSAGE_ID(CREATEDOMAINSHADER_INVALIDCLASSLINKAGE),
                MESSAGE_ID(RESOURCE_UNMAP_NOTMAPPED),
                MESSAGE_ID(DEVICE_CHECKFEATURESUPPORT_MISMATCHED_DATA_SIZE),
                MESSAGE_ID(CREATECOMPUTESHADER_OUTOFMEMORY),
                MESSAGE_ID(CREATECOMPUTESHADER_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATECOMPUTESHADER_INVALIDCLASSLINKAGE),
                MESSAGE_ID(DEVICE_CREATEVERTEXSHADER_DOUBLEFLOATOPSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEHULLSHADER_DOUBLEFLOATOPSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEDOMAINSHADER_DOUBLEFLOATOPSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEGEOMETRYSHADER_DOUBLEFLOATOPSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DOUBLEFLOATOPSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEPIXELSHADER_DOUBLEFLOATOPSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATECOMPUTESHADER_DOUBLEFLOATOPSNOTSUPPORTED),
                MESSAGE_ID(CREATEUNORDEREDACCESSVIEW_INVALIDRESOURCE),
                MESSAGE_ID(CREATEUNORDEREDACCESSVIEW_INVALIDDESC),
                MESSAGE_ID(CREATEUNORDEREDACCESSVIEW_INVALIDFORMAT),
                MESSAGE_ID(CREATEUNORDEREDACCESSVIEW_INVALIDVIDEOPLANESLICE),
                MESSAGE_ID(CREATEUNORDEREDACCESSVIEW_INVALIDPLANESLICE),
                MESSAGE_ID(CREATEUNORDEREDACCESSVIEW_INVALIDDIMENSIONS),
                MESSAGE_ID(CREATEUNORDEREDACCESSVIEW_UNRECOGNIZEDFORMAT),
                MESSAGE_ID(CREATEUNORDEREDACCESSVIEW_INVALIDFLAGS),
                MESSAGE_ID(CREATERASTERIZERSTATE_INVALIDFORCEDSAMPLECOUNT),
                MESSAGE_ID(CREATEBLENDSTATE_INVALIDLOGICOPS),
                MESSAGE_ID(DEVICE_CREATEVERTEXSHADER_DOUBLEEXTENSIONSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEHULLSHADER_DOUBLEEXTENSIONSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEDOMAINSHADER_DOUBLEEXTENSIONSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEGEOMETRYSHADER_DOUBLEEXTENSIONSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DOUBLEEXTENSIONSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEPIXELSHADER_DOUBLEEXTENSIONSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATECOMPUTESHADER_DOUBLEEXTENSIONSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEVERTEXSHADER_UAVSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEHULLSHADER_UAVSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEDOMAINSHADER_UAVSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEGEOMETRYSHADER_UAVSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UAVSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATEPIXELSHADER_UAVSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CREATECOMPUTESHADER_UAVSNOTSUPPORTED),
                MESSAGE_ID(DEVICE_CLEARVIEW_INVALIDSOURCERECT),
                MESSAGE_ID(DEVICE_CLEARVIEW_EMPTYRECT),
                MESSAGE_ID(UPDATETILEMAPPINGS_INVALID_PARAMETER),
                MESSAGE_ID(COPYTILEMAPPINGS_INVALID_PARAMETER),
                MESSAGE_ID(CREATEDEVICE_INVALIDARGS),
                MESSAGE_ID(CREATEDEVICE_WARNING),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_TYPE),
                MESSAGE_ID(RESOURCE_BARRIER_NULL_POINTER),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_SUBRESOURCE),
                MESSAGE_ID(RESOURCE_BARRIER_RESERVED_BITS),
                MESSAGE_ID(RESOURCE_BARRIER_MISSING_BIND_FLAGS),
                MESSAGE_ID(RESOURCE_BARRIER_MISMATCHING_MISC_FLAGS),
                MESSAGE_ID(RESOURCE_BARRIER_MATCHING_STATES),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_COMBINATION),
                MESSAGE_ID(RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_RESOURCE),
                MESSAGE_ID(RESOURCE_BARRIER_SAMPLE_COUNT),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_FLAGS),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_COMBINED_FLAGS),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_FLAGS_FOR_FORMAT),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_SPLIT_BARRIER),
                MESSAGE_ID(RESOURCE_BARRIER_UNMATCHED_END),
                MESSAGE_ID(RESOURCE_BARRIER_UNMATCHED_BEGIN),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_FLAG),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_COMMAND_LIST_TYPE),
                MESSAGE_ID(INVALID_SUBRESOURCE_STATE),
                MESSAGE_ID(COMMAND_ALLOCATOR_CONTENTION),
                MESSAGE_ID(COMMAND_ALLOCATOR_RESET),
                MESSAGE_ID(COMMAND_ALLOCATOR_RESET_BUNDLE),
                MESSAGE_ID(COMMAND_ALLOCATOR_CANNOT_RESET),
                MESSAGE_ID(COMMAND_LIST_OPEN),
                MESSAGE_ID(INVALID_BUNDLE_API),
                MESSAGE_ID(COMMAND_LIST_CLOSED),
                MESSAGE_ID(WRONG_COMMAND_ALLOCATOR_TYPE),
                MESSAGE_ID(COMMAND_ALLOCATOR_SYNC),
                MESSAGE_ID(COMMAND_LIST_SYNC),
                MESSAGE_ID(SET_DESCRIPTOR_HEAP_INVALID),
                MESSAGE_ID(CREATE_COMMANDQUEUE),
                MESSAGE_ID(CREATE_COMMANDALLOCATOR),
                MESSAGE_ID(CREATE_PIPELINESTATE),
                MESSAGE_ID(CREATE_COMMANDLIST12),
                MESSAGE_ID(CREATE_RESOURCE),
                MESSAGE_ID(CREATE_DESCRIPTORHEAP),
                MESSAGE_ID(CREATE_ROOTSIGNATURE),
                MESSAGE_ID(CREATE_LIBRARY),
                MESSAGE_ID(CREATE_HEAP),
                MESSAGE_ID(CREATE_MONITOREDFENCE),
                MESSAGE_ID(CREATE_QUERYHEAP),
                MESSAGE_ID(CREATE_COMMANDSIGNATURE),
                MESSAGE_ID(LIVE_COMMANDQUEUE),
                MESSAGE_ID(LIVE_COMMANDALLOCATOR),
                MESSAGE_ID(LIVE_PIPELINESTATE),
                MESSAGE_ID(LIVE_COMMANDLIST12),
                MESSAGE_ID(LIVE_RESOURCE),
                MESSAGE_ID(LIVE_DESCRIPTORHEAP),
                MESSAGE_ID(LIVE_ROOTSIGNATURE),
                MESSAGE_ID(LIVE_LIBRARY),
                MESSAGE_ID(LIVE_HEAP),
                MESSAGE_ID(LIVE_MONITOREDFENCE),
                MESSAGE_ID(LIVE_QUERYHEAP),
                MESSAGE_ID(LIVE_COMMANDSIGNATURE),
                MESSAGE_ID(DESTROY_COMMANDQUEUE),
                MESSAGE_ID(DESTROY_COMMANDALLOCATOR),
                MESSAGE_ID(DESTROY_PIPELINESTATE),
                MESSAGE_ID(DESTROY_COMMANDLIST12),
                MESSAGE_ID(DESTROY_RESOURCE),
                MESSAGE_ID(DESTROY_DESCRIPTORHEAP),
                MESSAGE_ID(DESTROY_ROOTSIGNATURE),
                MESSAGE_ID(DESTROY_LIBRARY),
                MESSAGE_ID(DESTROY_HEAP),
                MESSAGE_ID(DESTROY_MONITOREDFENCE),
                MESSAGE_ID(DESTROY_QUERYHEAP),
                MESSAGE_ID(DESTROY_COMMANDSIGNATURE),
                MESSAGE_ID(CREATERESOURCE_INVALIDDIMENSIONS),
                MESSAGE_ID(CREATERESOURCE_INVALIDMISCFLAGS),
                MESSAGE_ID(CREATERESOURCE_INVALIDARG_RETURN),
                MESSAGE_ID(CREATERESOURCE_OUTOFMEMORY_RETURN),
                MESSAGE_ID(CREATERESOURCE_INVALIDDESC),
                MESSAGE_ID(POSSIBLY_INVALID_SUBRESOURCE_STATE),
                MESSAGE_ID(INVALID_USE_OF_NON_RESIDENT_RESOURCE),
                MESSAGE_ID(POSSIBLE_INVALID_USE_OF_NON_RESIDENT_RESOURCE),
                MESSAGE_ID(BUNDLE_PIPELINE_STATE_MISMATCH),
                MESSAGE_ID(PRIMITIVE_TOPOLOGY_MISMATCH_PIPELINE_STATE),
                MESSAGE_ID(RENDER_TARGET_FORMAT_MISMATCH_PIPELINE_STATE),
                MESSAGE_ID(RENDER_TARGET_SAMPLE_DESC_MISMATCH_PIPELINE_STATE),
                MESSAGE_ID(DEPTH_STENCIL_FORMAT_MISMATCH_PIPELINE_STATE),
                MESSAGE_ID(DEPTH_STENCIL_SAMPLE_DESC_MISMATCH_PIPELINE_STATE),
                MESSAGE_ID(CREATESHADER_INVALIDBYTECODE),
                MESSAGE_ID(CREATEHEAP_NULLDESC),
                MESSAGE_ID(CREATEHEAP_INVALIDSIZE),
                MESSAGE_ID(CREATEHEAP_UNRECOGNIZEDHEAPTYPE),
                MESSAGE_ID(CREATEHEAP_UNRECOGNIZEDCPUPAGEPROPERTIES),
                MESSAGE_ID(CREATEHEAP_UNRECOGNIZEDMEMORYPOOL),
                MESSAGE_ID(CREATEHEAP_INVALIDPROPERTIES),
                MESSAGE_ID(CREATEHEAP_INVALIDALIGNMENT),
                MESSAGE_ID(CREATEHEAP_UNRECOGNIZEDMISCFLAGS),
                MESSAGE_ID(CREATEHEAP_INVALIDMISCFLAGS),
                MESSAGE_ID(CREATEHEAP_INVALIDARG_RETURN),
                MESSAGE_ID(CREATEHEAP_OUTOFMEMORY_RETURN),
                MESSAGE_ID(CREATERESOURCEANDHEAP_NULLHEAPPROPERTIES),
                MESSAGE_ID(CREATERESOURCEANDHEAP_UNRECOGNIZEDHEAPTYPE),
                MESSAGE_ID(CREATERESOURCEANDHEAP_UNRECOGNIZEDCPUPAGEPROPERTIES),
                MESSAGE_ID(CREATERESOURCEANDHEAP_UNRECOGNIZEDMEMORYPOOL),
                MESSAGE_ID(CREATERESOURCEANDHEAP_INVALIDHEAPPROPERTIES),
                MESSAGE_ID(CREATERESOURCEANDHEAP_UNRECOGNIZEDHEAPMISCFLAGS),
                MESSAGE_ID(CREATERESOURCEANDHEAP_INVALIDHEAPMISCFLAGS),
                MESSAGE_ID(CREATERESOURCEANDHEAP_INVALIDARG_RETURN),
                MESSAGE_ID(CREATERESOURCEANDHEAP_OUTOFMEMORY_RETURN),
                MESSAGE_ID(GETCUSTOMHEAPPROPERTIES_UNRECOGNIZEDHEAPTYPE),
                MESSAGE_ID(GETCUSTOMHEAPPROPERTIES_INVALIDHEAPTYPE),
                MESSAGE_ID(CREATE_DESCRIPTOR_HEAP_INVALID_DESC),
                MESSAGE_ID(INVALID_DESCRIPTOR_HANDLE),
                MESSAGE_ID(CREATERASTERIZERSTATE_INVALID_CONSERVATIVERASTERMODE),
                MESSAGE_ID(CREATE_CONSTANT_BUFFER_VIEW_INVALID_RESOURCE),
                MESSAGE_ID(CREATE_CONSTANT_BUFFER_VIEW_INVALID_DESC),
                MESSAGE_ID(CREATE_UNORDEREDACCESS_VIEW_INVALID_COUNTER_USAGE),
                MESSAGE_ID(COPY_DESCRIPTORS_INVALID_RANGES),
                MESSAGE_ID(COPY_DESCRIPTORS_WRITE_ONLY_DESCRIPTOR),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_RTV_FORMAT_NOT_UNKNOWN),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INVALID_RENDER_TARGET_COUNT),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_VERTEX_SHADER_NOT_SET),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INPUTLAYOUT_NOT_SET),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_HS_DS_SIGNATURE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_REGISTERINDEX),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_COMPONENTTYPE),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_REGISTERMASK),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SYSTEMVALUE),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_MINPRECISION),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_HS_XOR_DS_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_HULL_SHADER_INPUT_TOPOLOGY_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_HS_DS_CONTROL_POINT_COUNT_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_HS_DS_TESSELLATOR_DOMAIN_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INVALID_USE_OF_FORCED_SAMPLE_COUNT),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INVALID_PRIMITIVETOPOLOGY),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INVALID_SYSTEMVALUE),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_PS_OUTPUT_TYPE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_OM_RENDER_TARGET_DOES_NOT_SUPPORT_LOGIC_OPS),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_RENDERTARGETVIEW_NOT_SET),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_DEPTHSTENCILVIEW_NOT_SET),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_GS_INPUT_PRIMITIVE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_POSITION_NOT_PRESENT),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_MISSING_ROOT_SIGNATURE_FLAGS),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INVALID_INDEX_BUFFER_PROPERTIES),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INVALID_SAMPLE_DESC),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_HS_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_DS_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_VS_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_GS_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_PS_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_MISSING_ROOT_SIGNATURE),
                MESSAGE_ID(EXECUTE_BUNDLE_OPEN_BUNDLE),
                MESSAGE_ID(EXECUTE_BUNDLE_DESCRIPTOR_HEAP_MISMATCH),
                MESSAGE_ID(EXECUTE_BUNDLE_TYPE),
                MESSAGE_ID(DRAW_EMPTY_SCISSOR_RECTANGLE),
                MESSAGE_ID(CREATE_ROOT_SIGNATURE_BLOB_NOT_FOUND),
                MESSAGE_ID(CREATE_ROOT_SIGNATURE_DESERIALIZE_FAILED),
                MESSAGE_ID(CREATE_ROOT_SIGNATURE_INVALID_CONFIGURATION),
                MESSAGE_ID(CREATE_ROOT_SIGNATURE_NOT_SUPPORTED_ON_DEVICE),
                MESSAGE_ID(CREATERESOURCEANDHEAP_NULLRESOURCEPROPERTIES),
                MESSAGE_ID(CREATERESOURCEANDHEAP_NULLHEAP),
                MESSAGE_ID(GETRESOURCEALLOCATIONINFO_INVALIDRDESCS),
                MESSAGE_ID(MAKERESIDENT_NULLOBJECTARRAY),
                MESSAGE_ID(EVICT_NULLOBJECTARRAY),
                MESSAGE_ID(SET_DESCRIPTOR_TABLE_INVALID),
                MESSAGE_ID(SET_ROOT_CONSTANT_INVALID),
                MESSAGE_ID(SET_ROOT_CONSTANT_BUFFER_VIEW_INVALID),
                MESSAGE_ID(SET_ROOT_SHADER_RESOURCE_VIEW_INVALID),
                MESSAGE_ID(SET_ROOT_UNORDERED_ACCESS_VIEW_INVALID),
                MESSAGE_ID(SET_VERTEX_BUFFERS_INVALID_DESC),
                MESSAGE_ID(SET_INDEX_BUFFER_INVALID_DESC),
                MESSAGE_ID(SET_STREAM_OUTPUT_BUFFERS_INVALID_DESC),
                MESSAGE_ID(CREATERESOURCE_UNRECOGNIZEDDIMENSIONALITY),
                MESSAGE_ID(CREATERESOURCE_UNRECOGNIZEDLAYOUT),
                MESSAGE_ID(CREATERESOURCE_INVALIDDIMENSIONALITY),
                MESSAGE_ID(CREATERESOURCE_INVALIDALIGNMENT),
                MESSAGE_ID(CREATERESOURCE_INVALIDMIPLEVELS),
                MESSAGE_ID(CREATERESOURCE_INVALIDSAMPLEDESC),
                MESSAGE_ID(CREATERESOURCE_INVALIDLAYOUT),
                MESSAGE_ID(SET_INDEX_BUFFER_INVALID),
                MESSAGE_ID(SET_VERTEX_BUFFERS_INVALID),
                MESSAGE_ID(SET_STREAM_OUTPUT_BUFFERS_INVALID),
                MESSAGE_ID(SET_RENDER_TARGETS_INVALID),
                MESSAGE_ID(CREATEQUERY_HEAP_INVALID_PARAMETERS),
                MESSAGE_ID(BEGIN_END_QUERY_INVALID_PARAMETERS),
                MESSAGE_ID(CLOSE_COMMAND_LIST_OPEN_QUERY),
                MESSAGE_ID(RESOLVE_QUERY_DATA_INVALID_PARAMETERS),
                MESSAGE_ID(SET_PREDICATION_INVALID_PARAMETERS),
                MESSAGE_ID(TIMESTAMPS_NOT_SUPPORTED),
                MESSAGE_ID(CREATERESOURCE_UNRECOGNIZEDFORMAT),
                MESSAGE_ID(CREATERESOURCE_INVALIDFORMAT),
                MESSAGE_ID(GETCOPYABLEFOOTPRINTS_INVALIDSUBRESOURCERANGE),
                MESSAGE_ID(GETCOPYABLEFOOTPRINTS_INVALIDBASEOFFSET),
                MESSAGE_ID(GETCOPYABLELAYOUT_INVALIDSUBRESOURCERANGE),
                MESSAGE_ID(GETCOPYABLELAYOUT_INVALIDBASEOFFSET),
                MESSAGE_ID(RESOURCE_BARRIER_INVALID_HEAP),
                MESSAGE_ID(CREATE_SAMPLER_INVALID),
                MESSAGE_ID(CREATECOMMANDSIGNATURE_INVALID),
                MESSAGE_ID(EXECUTE_INDIRECT_INVALID_PARAMETERS),
                MESSAGE_ID(GETGPUVIRTUALADDRESS_INVALID_RESOURCE_DIMENSION),
                MESSAGE_ID(CREATERESOURCE_INVALIDCLEARVALUE),
                MESSAGE_ID(CREATERESOURCE_UNRECOGNIZEDCLEARVALUEFORMAT),
                MESSAGE_ID(CREATERESOURCE_INVALIDCLEARVALUEFORMAT),
                MESSAGE_ID(CREATERESOURCE_CLEARVALUEDENORMFLUSH),
                MESSAGE_ID(CLEARRENDERTARGETVIEW_MISMATCHINGCLEARVALUE),
                MESSAGE_ID(CLEARDEPTHSTENCILVIEW_MISMATCHINGCLEARVALUE),
                MESSAGE_ID(MAP_INVALIDHEAP),
                MESSAGE_ID(UNMAP_INVALIDHEAP),
                MESSAGE_ID(MAP_INVALIDRESOURCE),
                MESSAGE_ID(UNMAP_INVALIDRESOURCE),
                MESSAGE_ID(MAP_INVALIDSUBRESOURCE),
                MESSAGE_ID(UNMAP_INVALIDSUBRESOURCE),
                MESSAGE_ID(MAP_INVALIDRANGE),
                MESSAGE_ID(UNMAP_INVALIDRANGE),
                MESSAGE_ID(MAP_INVALIDDATAPOINTER),
                MESSAGE_ID(MAP_INVALIDARG_RETURN),
                MESSAGE_ID(MAP_OUTOFMEMORY_RETURN),
                MESSAGE_ID(EXECUTECOMMANDLISTS_BUNDLENOTSUPPORTED),
                MESSAGE_ID(EXECUTECOMMANDLISTS_COMMANDLISTMISMATCH),
                MESSAGE_ID(EXECUTECOMMANDLISTS_OPENCOMMANDLIST),
                MESSAGE_ID(EXECUTECOMMANDLISTS_FAILEDCOMMANDLIST),
                MESSAGE_ID(COPYBUFFERREGION_NULLDST),
                MESSAGE_ID(COPYBUFFERREGION_INVALIDDSTRESOURCEDIMENSION),
                MESSAGE_ID(COPYBUFFERREGION_DSTRANGEOUTOFBOUNDS),
                MESSAGE_ID(COPYBUFFERREGION_NULLSRC),
                MESSAGE_ID(COPYBUFFERREGION_INVALIDSRCRESOURCEDIMENSION),
                MESSAGE_ID(COPYBUFFERREGION_SRCRANGEOUTOFBOUNDS),
                MESSAGE_ID(COPYBUFFERREGION_INVALIDCOPYFLAGS),
                MESSAGE_ID(COPYTEXTUREREGION_NULLDST),
                MESSAGE_ID(COPYTEXTUREREGION_UNRECOGNIZEDDSTTYPE),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTRESOURCEDIMENSION),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTRESOURCE),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTSUBRESOURCE),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTOFFSET),
                MESSAGE_ID(COPYTEXTUREREGION_UNRECOGNIZEDDSTFORMAT),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTFORMAT),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTDIMENSIONS),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTROWPITCH),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTPLACEMENT),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTDSPLACEDFOOTPRINTFORMAT),
                MESSAGE_ID(COPYTEXTUREREGION_DSTREGIONOUTOFBOUNDS),
                MESSAGE_ID(COPYTEXTUREREGION_NULLSRC),
                MESSAGE_ID(COPYTEXTUREREGION_UNRECOGNIZEDSRCTYPE),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCRESOURCEDIMENSION),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCRESOURCE),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCSUBRESOURCE),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCOFFSET),
                MESSAGE_ID(COPYTEXTUREREGION_UNRECOGNIZEDSRCFORMAT),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCFORMAT),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCDIMENSIONS),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCROWPITCH),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCPLACEMENT),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCDSPLACEDFOOTPRINTFORMAT),
                MESSAGE_ID(COPYTEXTUREREGION_SRCREGIONOUTOFBOUNDS),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDDSTCOORDINATES),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDSRCBOX),
                MESSAGE_ID(COPYTEXTUREREGION_FORMATMISMATCH),
                MESSAGE_ID(COPYTEXTUREREGION_EMPTYBOX),
                MESSAGE_ID(COPYTEXTUREREGION_INVALIDCOPYFLAGS),
                MESSAGE_ID(RESOLVESUBRESOURCE_INVALID_SUBRESOURCE_INDEX),
                MESSAGE_ID(RESOLVESUBRESOURCE_INVALID_FORMAT),
                MESSAGE_ID(RESOLVESUBRESOURCE_RESOURCE_MISMATCH),
                MESSAGE_ID(RESOLVESUBRESOURCE_INVALID_SAMPLE_COUNT),
                MESSAGE_ID(CREATECOMPUTEPIPELINESTATE_INVALID_SHADER),
                MESSAGE_ID(CREATECOMPUTEPIPELINESTATE_CS_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(CREATECOMPUTEPIPELINESTATE_MISSING_ROOT_SIGNATURE),
                MESSAGE_ID(CREATEPIPELINESTATE_INVALIDCACHEDBLOB),
                MESSAGE_ID(CREATEPIPELINESTATE_CACHEDBLOBADAPTERMISMATCH),
                MESSAGE_ID(CREATEPIPELINESTATE_CACHEDBLOBDRIVERVERSIONMISMATCH),
                MESSAGE_ID(CREATEPIPELINESTATE_CACHEDBLOBDESCMISMATCH),
                MESSAGE_ID(CREATEPIPELINESTATE_CACHEDBLOBIGNORED),
                MESSAGE_ID(WRITETOSUBRESOURCE_INVALIDHEAP),
                MESSAGE_ID(WRITETOSUBRESOURCE_INVALIDRESOURCE),
                MESSAGE_ID(WRITETOSUBRESOURCE_INVALIDBOX),
                MESSAGE_ID(WRITETOSUBRESOURCE_INVALIDSUBRESOURCE),
                MESSAGE_ID(WRITETOSUBRESOURCE_EMPTYBOX),
                MESSAGE_ID(READFROMSUBRESOURCE_INVALIDHEAP),
                MESSAGE_ID(READFROMSUBRESOURCE_INVALIDRESOURCE),
                MESSAGE_ID(READFROMSUBRESOURCE_INVALIDBOX),
                MESSAGE_ID(READFROMSUBRESOURCE_INVALIDSUBRESOURCE),
                MESSAGE_ID(READFROMSUBRESOURCE_EMPTYBOX),
                MESSAGE_ID(TOO_MANY_NODES_SPECIFIED),
                MESSAGE_ID(INVALID_NODE_INDEX),
                MESSAGE_ID(GETHEAPPROPERTIES_INVALIDRESOURCE),
                MESSAGE_ID(NODE_MASK_MISMATCH),
                MESSAGE_ID(COMMAND_LIST_OUTOFMEMORY),
                MESSAGE_ID(COMMAND_LIST_MULTIPLE_SWAPCHAIN_BUFFER_REFERENCES),
                MESSAGE_ID(COMMAND_LIST_TOO_MANY_SWAPCHAIN_REFERENCES),
                MESSAGE_ID(COMMAND_QUEUE_TOO_MANY_SWAPCHAIN_REFERENCES),
                MESSAGE_ID(EXECUTECOMMANDLISTS_WRONGSWAPCHAINBUFFERREFERENCE),
                MESSAGE_ID(COMMAND_LIST_SETRENDERTARGETS_INVALIDNUMRENDERTARGETS),
                MESSAGE_ID(CREATE_QUEUE_INVALID_TYPE),
                MESSAGE_ID(CREATE_QUEUE_INVALID_FLAGS),
                MESSAGE_ID(CREATESHAREDRESOURCE_INVALIDFLAGS),
                MESSAGE_ID(CREATESHAREDRESOURCE_INVALIDFORMAT),
                MESSAGE_ID(CREATESHAREDHEAP_INVALIDFLAGS),
                MESSAGE_ID(REFLECTSHAREDPROPERTIES_UNRECOGNIZEDPROPERTIES),
                MESSAGE_ID(REFLECTSHAREDPROPERTIES_INVALIDSIZE),
                MESSAGE_ID(REFLECTSHAREDPROPERTIES_INVALIDOBJECT),
                MESSAGE_ID(KEYEDMUTEX_INVALIDOBJECT),
                MESSAGE_ID(KEYEDMUTEX_INVALIDKEY),
                MESSAGE_ID(KEYEDMUTEX_WRONGSTATE),
                MESSAGE_ID(CREATE_QUEUE_INVALID_PRIORITY),
                MESSAGE_ID(OBJECT_DELETED_WHILE_STILL_IN_USE),
                MESSAGE_ID(CREATEPIPELINESTATE_INVALID_FLAGS),
                MESSAGE_ID(HEAP_ADDRESS_RANGE_HAS_NO_RESOURCE),
                MESSAGE_ID(COMMAND_LIST_DRAW_RENDER_TARGET_DELETED),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_ALL_RENDER_TARGETS_HAVE_UNKNOWN_FORMAT),
                MESSAGE_ID(HEAP_ADDRESS_RANGE_INTERSECTS_MULTIPLE_BUFFERS),
                MESSAGE_ID(EXECUTECOMMANDLISTS_GPU_WRITTEN_READBACK_RESOURCE_MAPPED),
                MESSAGE_ID(UNMAP_RANGE_NOT_EMPTY),
                MESSAGE_ID(MAP_INVALID_NULLRANGE),
                MESSAGE_ID(UNMAP_INVALID_NULLRANGE),
                MESSAGE_ID(NO_GRAPHICS_API_SUPPORT),
                MESSAGE_ID(NO_COMPUTE_API_SUPPORT),
                MESSAGE_ID(RESOLVESUBRESOURCE_RESOURCE_FLAGS_NOT_SUPPORTED),
                MESSAGE_ID(GPU_BASED_VALIDATION_ROOT_ARGUMENT_UNINITIALIZED),
                MESSAGE_ID(GPU_BASED_VALIDATION_DESCRIPTOR_HEAP_INDEX_OUT_OF_BOUNDS),
                MESSAGE_ID(GPU_BASED_VALIDATION_DESCRIPTOR_TABLE_REGISTER_INDEX_OUT_OF_BOUNDS),
                MESSAGE_ID(GPU_BASED_VALIDATION_DESCRIPTOR_UNINITIALIZED),
                MESSAGE_ID(GPU_BASED_VALIDATION_DESCRIPTOR_TYPE_MISMATCH),
                MESSAGE_ID(GPU_BASED_VALIDATION_SRV_RESOURCE_DIMENSION_MISMATCH),
                MESSAGE_ID(GPU_BASED_VALIDATION_UAV_RESOURCE_DIMENSION_MISMATCH),
                MESSAGE_ID(GPU_BASED_VALIDATION_INCOMPATIBLE_RESOURCE_STATE),
                MESSAGE_ID(COPYRESOURCE_NULLDST),
                MESSAGE_ID(COPYRESOURCE_INVALIDDSTRESOURCE),
                MESSAGE_ID(COPYRESOURCE_NULLSRC),
                MESSAGE_ID(COPYRESOURCE_INVALIDSRCRESOURCE),
                MESSAGE_ID(RESOLVESUBRESOURCE_NULLDST),
                MESSAGE_ID(RESOLVESUBRESOURCE_INVALIDDSTRESOURCE),
                MESSAGE_ID(RESOLVESUBRESOURCE_NULLSRC),
                MESSAGE_ID(RESOLVESUBRESOURCE_INVALIDSRCRESOURCE),
                MESSAGE_ID(PIPELINE_STATE_TYPE_MISMATCH),
                MESSAGE_ID(COMMAND_LIST_DISPATCH_ROOT_SIGNATURE_NOT_SET),
                MESSAGE_ID(COMMAND_LIST_DISPATCH_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(RESOURCE_BARRIER_ZERO_BARRIERS),
                MESSAGE_ID(BEGIN_END_EVENT_MISMATCH),
                MESSAGE_ID(RESOURCE_BARRIER_POSSIBLE_BEFORE_AFTER_MISMATCH),
                MESSAGE_ID(RESOURCE_BARRIER_MISMATCHING_BEGIN_END),
                MESSAGE_ID(GPU_BASED_VALIDATION_INVALID_RESOURCE),
                MESSAGE_ID(USE_OF_ZERO_REFCOUNT_OBJECT),
                MESSAGE_ID(OBJECT_EVICTED_WHILE_STILL_IN_USE),
                MESSAGE_ID(GPU_BASED_VALIDATION_ROOT_DESCRIPTOR_ACCESS_OUT_OF_BOUNDS),
                MESSAGE_ID(CREATEPIPELINELIBRARY_INVALIDLIBRARYBLOB),
                MESSAGE_ID(CREATEPIPELINELIBRARY_DRIVERVERSIONMISMATCH),
                MESSAGE_ID(CREATEPIPELINELIBRARY_ADAPTERVERSIONMISMATCH),
                MESSAGE_ID(CREATEPIPELINELIBRARY_UNSUPPORTED),
                MESSAGE_ID(CREATE_PIPELINELIBRARY),
                MESSAGE_ID(LIVE_PIPELINELIBRARY),
                MESSAGE_ID(DESTROY_PIPELINELIBRARY),
                MESSAGE_ID(STOREPIPELINE_NONAME),
                MESSAGE_ID(STOREPIPELINE_DUPLICATENAME),
                MESSAGE_ID(LOADPIPELINE_NAMENOTFOUND),
                MESSAGE_ID(LOADPIPELINE_INVALIDDESC),
                MESSAGE_ID(PIPELINELIBRARY_SERIALIZE_NOTENOUGHMEMORY),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_PS_OUTPUT_RT_OUTPUT_MISMATCH),
                MESSAGE_ID(SETEVENTONMULTIPLEFENCECOMPLETION_INVALIDFLAGS),
                MESSAGE_ID(CREATE_QUEUE_VIDEO_NOT_SUPPORTED),
                MESSAGE_ID(CREATE_COMMAND_ALLOCATOR_VIDEO_NOT_SUPPORTED),
                MESSAGE_ID(CREATEQUERY_HEAP_VIDEO_DECODE_STATISTICS_NOT_SUPPORTED),
                MESSAGE_ID(CREATE_VIDEODECODECOMMANDLIST),
                MESSAGE_ID(CREATE_VIDEODECODER),
                MESSAGE_ID(CREATE_VIDEODECODESTREAM),
                MESSAGE_ID(LIVE_VIDEODECODECOMMANDLIST),
                MESSAGE_ID(LIVE_VIDEODECODER),
                MESSAGE_ID(LIVE_VIDEODECODESTREAM),
                MESSAGE_ID(DESTROY_VIDEODECODECOMMANDLIST),
                MESSAGE_ID(DESTROY_VIDEODECODER),
                MESSAGE_ID(DESTROY_VIDEODECODESTREAM),
                MESSAGE_ID(DECODE_FRAME_INVALID_PARAMETERS),
                MESSAGE_ID(DEPRECATED_API),
                MESSAGE_ID(RESOURCE_BARRIER_MISMATCHING_COMMAND_LIST_TYPE),
                MESSAGE_ID(COMMAND_LIST_DESCRIPTOR_TABLE_NOT_SET),
                MESSAGE_ID(COMMAND_LIST_ROOT_CONSTANT_BUFFER_VIEW_NOT_SET),
                MESSAGE_ID(COMMAND_LIST_ROOT_SHADER_RESOURCE_VIEW_NOT_SET),
                MESSAGE_ID(COMMAND_LIST_ROOT_UNORDERED_ACCESS_VIEW_NOT_SET),
                MESSAGE_ID(DISCARD_INVALID_SUBRESOURCE_RANGE),
                MESSAGE_ID(DISCARD_ONE_SUBRESOURCE_FOR_MIPS_WITH_RECTS),
                MESSAGE_ID(DISCARD_NO_RECTS_FOR_NON_TEXTURE2D),
                MESSAGE_ID(COPY_ON_SAME_SUBRESOURCE),
                MESSAGE_ID(SETRESIDENCYPRIORITY_INVALID_PAGEABLE),
                MESSAGE_ID(GPU_BASED_VALIDATION_UNSUPPORTED),
                MESSAGE_ID(STATIC_DESCRIPTOR_INVALID_DESCRIPTOR_CHANGE),
                MESSAGE_ID(DATA_STATIC_DESCRIPTOR_INVALID_DATA_CHANGE),
                MESSAGE_ID(DATA_STATIC_WHILE_SET_AT_EXECUTE_DESCRIPTOR_INVALID_DATA_CHANGE),
                MESSAGE_ID(EXECUTE_BUNDLE_STATIC_DESCRIPTOR_DATA_STATIC_NOT_SET),
                MESSAGE_ID(GPU_BASED_VALIDATION_RESOURCE_ACCESS_OUT_OF_BOUNDS),
                MESSAGE_ID(GPU_BASED_VALIDATION_SAMPLER_MODE_MISMATCH),
                MESSAGE_ID(CREATE_FENCE_INVALID_FLAGS),
                MESSAGE_ID(RESOURCE_BARRIER_DUPLICATE_SUBRESOURCE_TRANSITIONS),
                MESSAGE_ID(SETRESIDENCYPRIORITY_INVALID_PRIORITY),
                MESSAGE_ID(CREATE_DESCRIPTOR_HEAP_LARGE_NUM_DESCRIPTORS),
                MESSAGE_ID(BEGIN_EVENT),
                MESSAGE_ID(END_EVENT),
                MESSAGE_ID(CREATEDEVICE_DEBUG_LAYER_STARTUP_OPTIONS),
                MESSAGE_ID(CREATEDEPTHSTENCILSTATE_DEPTHBOUNDSTEST_UNSUPPORTED),
                MESSAGE_ID(CREATEPIPELINESTATE_DUPLICATE_SUBOBJECT),
                MESSAGE_ID(CREATEPIPELINESTATE_UNKNOWN_SUBOBJECT),
                MESSAGE_ID(CREATEPIPELINESTATE_ZERO_SIZE_STREAM),
                MESSAGE_ID(CREATEPIPELINESTATE_INVALID_STREAM),
                MESSAGE_ID(CREATEPIPELINESTATE_CANNOT_DEDUCE_TYPE),
                MESSAGE_ID(COMMAND_LIST_STATIC_DESCRIPTOR_RESOURCE_DIMENSION_MISMATCH),
                MESSAGE_ID(CREATE_COMMAND_QUEUE_INSUFFICIENT_PRIVILEGE_FOR_GLOBAL_REALTIME),
                MESSAGE_ID(CREATE_COMMAND_QUEUE_INSUFFICIENT_HARDWARE_SUPPORT_FOR_GLOBAL_REALTIME),
                MESSAGE_ID(ATOMICCOPYBUFFER_INVALID_ARCHITECTURE),
                MESSAGE_ID(ATOMICCOPYBUFFER_NULL_DST),
                MESSAGE_ID(ATOMICCOPYBUFFER_INVALID_DST_RESOURCE_DIMENSION),
                MESSAGE_ID(ATOMICCOPYBUFFER_DST_RANGE_OUT_OF_BOUNDS),
                MESSAGE_ID(ATOMICCOPYBUFFER_NULL_SRC),
                MESSAGE_ID(ATOMICCOPYBUFFER_INVALID_SRC_RESOURCE_DIMENSION),
                MESSAGE_ID(ATOMICCOPYBUFFER_SRC_RANGE_OUT_OF_BOUNDS),
                MESSAGE_ID(ATOMICCOPYBUFFER_INVALID_OFFSET_ALIGNMENT),
                MESSAGE_ID(ATOMICCOPYBUFFER_NULL_DEPENDENT_RESOURCES),
                MESSAGE_ID(ATOMICCOPYBUFFER_NULL_DEPENDENT_SUBRESOURCE_RANGES),
                MESSAGE_ID(ATOMICCOPYBUFFER_INVALID_DEPENDENT_RESOURCE),
                MESSAGE_ID(ATOMICCOPYBUFFER_INVALID_DEPENDENT_SUBRESOURCE_RANGE),
                MESSAGE_ID(ATOMICCOPYBUFFER_DEPENDENT_SUBRESOURCE_OUT_OF_BOUNDS),
                MESSAGE_ID(ATOMICCOPYBUFFER_DEPENDENT_RANGE_OUT_OF_BOUNDS),
                MESSAGE_ID(ATOMICCOPYBUFFER_ZERO_DEPENDENCIES),
                MESSAGE_ID(DEVICE_CREATE_SHARED_HANDLE_INVALIDARG),
                MESSAGE_ID(DESCRIPTOR_HANDLE_WITH_INVALID_RESOURCE),
                MESSAGE_ID(SETDEPTHBOUNDS_INVALIDARGS),
                MESSAGE_ID(GPU_BASED_VALIDATION_RESOURCE_STATE_IMPRECISE),
                MESSAGE_ID(COMMAND_LIST_PIPELINE_STATE_NOT_SET),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_SHADER_MODEL_MISMATCH),
                MESSAGE_ID(OBJECT_ACCESSED_WHILE_STILL_IN_USE),
                MESSAGE_ID(PROGRAMMABLE_MSAA_UNSUPPORTED),
                MESSAGE_ID(SETSAMPLEPOSITIONS_INVALIDARGS),
                MESSAGE_ID(RESOLVESUBRESOURCEREGION_INVALID_RECT),
                MESSAGE_ID(CREATE_VIDEODECODECOMMANDQUEUE),
                MESSAGE_ID(CREATE_VIDEOPROCESSCOMMANDLIST),
                MESSAGE_ID(CREATE_VIDEOPROCESSCOMMANDQUEUE),
                MESSAGE_ID(LIVE_VIDEODECODECOMMANDQUEUE),
                MESSAGE_ID(LIVE_VIDEOPROCESSCOMMANDLIST),
                MESSAGE_ID(LIVE_VIDEOPROCESSCOMMANDQUEUE),
                MESSAGE_ID(DESTROY_VIDEODECODECOMMANDQUEUE),
                MESSAGE_ID(DESTROY_VIDEOPROCESSCOMMANDLIST),
                MESSAGE_ID(DESTROY_VIDEOPROCESSCOMMANDQUEUE),
                MESSAGE_ID(CREATE_VIDEOPROCESSOR),
                MESSAGE_ID(CREATE_VIDEOPROCESSSTREAM),
                MESSAGE_ID(LIVE_VIDEOPROCESSOR),
                MESSAGE_ID(LIVE_VIDEOPROCESSSTREAM),
                MESSAGE_ID(DESTROY_VIDEOPROCESSOR),
                MESSAGE_ID(DESTROY_VIDEOPROCESSSTREAM),
                MESSAGE_ID(PROCESS_FRAME_INVALID_PARAMETERS),
                MESSAGE_ID(COPY_INVALIDLAYOUT),
                MESSAGE_ID(CREATE_CRYPTO_SESSION),
                MESSAGE_ID(CREATE_CRYPTO_SESSION_POLICY),
                MESSAGE_ID(CREATE_PROTECTED_RESOURCE_SESSION),
                MESSAGE_ID(LIVE_CRYPTO_SESSION),
                MESSAGE_ID(LIVE_CRYPTO_SESSION_POLICY),
                MESSAGE_ID(LIVE_PROTECTED_RESOURCE_SESSION),
                MESSAGE_ID(DESTROY_CRYPTO_SESSION),
                MESSAGE_ID(DESTROY_CRYPTO_SESSION_POLICY),
                MESSAGE_ID(DESTROY_PROTECTED_RESOURCE_SESSION),
                MESSAGE_ID(PROTECTED_RESOURCE_SESSION_UNSUPPORTED),
                MESSAGE_ID(FENCE_INVALIDOPERATION),
                MESSAGE_ID(CREATEQUERY_HEAP_COPY_QUEUE_TIMESTAMPS_NOT_SUPPORTED),
                MESSAGE_ID(SAMPLEPOSITIONS_MISMATCH_DEFERRED),
                MESSAGE_ID(SAMPLEPOSITIONS_MISMATCH_RECORDTIME_ASSUMEDFROMFIRSTUSE),
                MESSAGE_ID(SAMPLEPOSITIONS_MISMATCH_RECORDTIME_ASSUMEDFROMCLEAR),
                MESSAGE_ID(CREATE_VIDEODECODERHEAP),
                MESSAGE_ID(LIVE_VIDEODECODERHEAP),
                MESSAGE_ID(DESTROY_VIDEODECODERHEAP),
                MESSAGE_ID(OPENEXISTINGHEAP_INVALIDARG_RETURN),
                MESSAGE_ID(OPENEXISTINGHEAP_OUTOFMEMORY_RETURN),
                MESSAGE_ID(OPENEXISTINGHEAP_INVALIDADDRESS),
                MESSAGE_ID(OPENEXISTINGHEAP_INVALIDHANDLE),
                MESSAGE_ID(WRITEBUFFERIMMEDIATE_INVALID_DEST),
                MESSAGE_ID(WRITEBUFFERIMMEDIATE_INVALID_MODE),
                MESSAGE_ID(WRITEBUFFERIMMEDIATE_INVALID_ALIGNMENT),
                MESSAGE_ID(WRITEBUFFERIMMEDIATE_NOT_SUPPORTED),
                MESSAGE_ID(SETVIEWINSTANCEMASK_INVALIDARGS),
                MESSAGE_ID(VIEW_INSTANCING_UNSUPPORTED),
                MESSAGE_ID(VIEW_INSTANCING_INVALIDARGS),
                MESSAGE_ID(COPYTEXTUREREGION_MISMATCH_DECODE_REFERENCE_ONLY_FLAG),
                MESSAGE_ID(COPYRESOURCE_MISMATCH_DECODE_REFERENCE_ONLY_FLAG),
                MESSAGE_ID(CREATE_VIDEO_DECODE_HEAP_CAPS_FAILURE),
                MESSAGE_ID(CREATE_VIDEO_DECODE_HEAP_CAPS_UNSUPPORTED),
                MESSAGE_ID(VIDEO_DECODE_SUPPORT_INVALID_INPUT),
                MESSAGE_ID(CREATE_VIDEO_DECODER_UNSUPPORTED),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_METADATA_ERROR),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_VIEW_INSTANCING_VERTEX_SIZE_EXCEEDED),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_RUNTIME_INTERNAL_ERROR),
                MESSAGE_ID(NO_VIDEO_API_SUPPORT),
                MESSAGE_ID(VIDEO_PROCESS_SUPPORT_INVALID_INPUT),
                MESSAGE_ID(CREATE_VIDEO_PROCESSOR_CAPS_FAILURE),
                MESSAGE_ID(VIDEO_PROCESS_SUPPORT_UNSUPPORTED_FORMAT),
                MESSAGE_ID(VIDEO_DECODE_FRAME_INVALID_ARGUMENT),
                MESSAGE_ID(ENQUEUE_MAKE_RESIDENT_INVALID_FLAGS),
                MESSAGE_ID(OPENEXISTINGHEAP_UNSUPPORTED),
                MESSAGE_ID(VIDEO_PROCESS_FRAMES_INVALID_ARGUMENT),
                MESSAGE_ID(VIDEO_DECODE_SUPPORT_UNSUPPORTED),
                MESSAGE_ID(CREATE_COMMANDRECORDER),
                MESSAGE_ID(LIVE_COMMANDRECORDER),
                MESSAGE_ID(DESTROY_COMMANDRECORDER),
                MESSAGE_ID(CREATE_COMMAND_RECORDER_VIDEO_NOT_SUPPORTED),
                MESSAGE_ID(CREATE_COMMAND_RECORDER_INVALID_SUPPORT_FLAGS),
                MESSAGE_ID(CREATE_COMMAND_RECORDER_INVALID_FLAGS),
                MESSAGE_ID(CREATE_COMMAND_RECORDER_MORE_RECORDERS_THAN_LOGICAL_PROCESSORS),
                MESSAGE_ID(CREATE_COMMANDPOOL),
                MESSAGE_ID(LIVE_COMMANDPOOL),
                MESSAGE_ID(DESTROY_COMMANDPOOL),
                MESSAGE_ID(CREATE_COMMAND_POOL_INVALID_FLAGS),
                MESSAGE_ID(CREATE_COMMAND_LIST_VIDEO_NOT_SUPPORTED),
                MESSAGE_ID(COMMAND_RECORDER_SUPPORT_FLAGS_MISMATCH),
                MESSAGE_ID(COMMAND_RECORDER_CONTENTION),
                MESSAGE_ID(COMMAND_RECORDER_USAGE_WITH_CREATECOMMANDLIST_COMMAND_LIST),
                MESSAGE_ID(COMMAND_ALLOCATOR_USAGE_WITH_CREATECOMMANDLIST1_COMMAND_LIST),
                MESSAGE_ID(CANNOT_EXECUTE_EMPTY_COMMAND_LIST),
                MESSAGE_ID(CANNOT_RESET_COMMAND_POOL_WITH_OPEN_COMMAND_LISTS),
                MESSAGE_ID(CANNOT_USE_COMMAND_RECORDER_WITHOUT_CURRENT_TARGET),
                MESSAGE_ID(CANNOT_CHANGE_COMMAND_RECORDER_TARGET_WHILE_RECORDING),
                MESSAGE_ID(COMMAND_POOL_SYNC),
                MESSAGE_ID(EVICT_UNDERFLOW),
                MESSAGE_ID(CREATE_META_COMMAND),
                MESSAGE_ID(LIVE_META_COMMAND),
                MESSAGE_ID(DESTROY_META_COMMAND),
                MESSAGE_ID(COPYBUFFERREGION_INVALID_DST_RESOURCE),
                MESSAGE_ID(COPYBUFFERREGION_INVALID_SRC_RESOURCE),
                MESSAGE_ID(ATOMICCOPYBUFFER_INVALID_DST_RESOURCE),
                MESSAGE_ID(ATOMICCOPYBUFFER_INVALID_SRC_RESOURCE),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_NULL_BUFFER),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_NULL_RESOURCE_DESC),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_UNSUPPORTED),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_INVALID_BUFFER_DIMENSION),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_INVALID_BUFFER_FLAGS),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_INVALID_BUFFER_OFFSET),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_INVALID_RESOURCE_DIMENSION),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_INVALID_RESOURCE_FLAGS),
                MESSAGE_ID(CREATEPLACEDRESOURCEONBUFFER_OUTOFMEMORY_RETURN),
                MESSAGE_ID(CANNOT_CREATE_GRAPHICS_AND_VIDEO_COMMAND_RECORDER),
                MESSAGE_ID(UPDATETILEMAPPINGS_POSSIBLY_MISMATCHING_PROPERTIES),
                MESSAGE_ID(CREATE_COMMAND_LIST_INVALID_COMMAND_LIST_TYPE),
                MESSAGE_ID(CLEARUNORDEREDACCESSVIEW_INCOMPATIBLE_WITH_STRUCTURED_BUFFERS),
                MESSAGE_ID(COMPUTE_ONLY_DEVICE_OPERATION_UNSUPPORTED),
                MESSAGE_ID(BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INVALID),
                MESSAGE_ID(EMIT_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_INVALID),
                MESSAGE_ID(COPY_RAYTRACING_ACCELERATION_STRUCTURE_INVALID),
                MESSAGE_ID(DISPATCH_RAYS_INVALID),
                MESSAGE_ID(GET_RAYTRACING_ACCELERATION_STRUCTURE_PREBUILD_INFO_INVALID),
                MESSAGE_ID(CREATE_LIFETIMETRACKER),
                MESSAGE_ID(LIVE_LIFETIMETRACKER),
                MESSAGE_ID(DESTROY_LIFETIMETRACKER),
                MESSAGE_ID(DESTROYOWNEDOBJECT_OBJECTNOTOWNED),
                MESSAGE_ID(CREATE_TRACKEDWORKLOAD),
                MESSAGE_ID(LIVE_TRACKEDWORKLOAD),
                MESSAGE_ID(DESTROY_TRACKEDWORKLOAD),
                MESSAGE_ID(RENDER_PASS_ERROR),
                MESSAGE_ID(META_COMMAND_ID_INVALID),
                MESSAGE_ID(META_COMMAND_UNSUPPORTED_PARAMS),
                MESSAGE_ID(META_COMMAND_FAILED_ENUMERATION),
                MESSAGE_ID(META_COMMAND_PARAMETER_SIZE_MISMATCH),
                MESSAGE_ID(UNINITIALIZED_META_COMMAND),
                MESSAGE_ID(META_COMMAND_INVALID_GPU_VIRTUAL_ADDRESS),
                MESSAGE_ID(CREATE_VIDEOENCODECOMMANDLIST),
                MESSAGE_ID(LIVE_VIDEOENCODECOMMANDLIST),
                MESSAGE_ID(DESTROY_VIDEOENCODECOMMANDLIST),
                MESSAGE_ID(CREATE_VIDEOENCODECOMMANDQUEUE),
                MESSAGE_ID(LIVE_VIDEOENCODECOMMANDQUEUE),
                MESSAGE_ID(DESTROY_VIDEOENCODECOMMANDQUEUE),
                MESSAGE_ID(CREATE_VIDEOMOTIONESTIMATOR),
                MESSAGE_ID(LIVE_VIDEOMOTIONESTIMATOR),
                MESSAGE_ID(DESTROY_VIDEOMOTIONESTIMATOR),
                MESSAGE_ID(CREATE_VIDEOMOTIONVECTORHEAP),
                MESSAGE_ID(LIVE_VIDEOMOTIONVECTORHEAP),
                MESSAGE_ID(DESTROY_VIDEOMOTIONVECTORHEAP),
                MESSAGE_ID(MULTIPLE_TRACKED_WORKLOADS),
                MESSAGE_ID(MULTIPLE_TRACKED_WORKLOAD_PAIRS),
                MESSAGE_ID(OUT_OF_ORDER_TRACKED_WORKLOAD_PAIR),
                MESSAGE_ID(CANNOT_ADD_TRACKED_WORKLOAD),
                MESSAGE_ID(INCOMPLETE_TRACKED_WORKLOAD_PAIR),
                MESSAGE_ID(CREATE_STATE_OBJECT_ERROR),
                MESSAGE_ID(GET_SHADER_IDENTIFIER_ERROR),
                MESSAGE_ID(GET_SHADER_STACK_SIZE_ERROR),
                MESSAGE_ID(GET_PIPELINE_STACK_SIZE_ERROR),
                MESSAGE_ID(SET_PIPELINE_STACK_SIZE_ERROR),
                MESSAGE_ID(GET_SHADER_IDENTIFIER_SIZE_INVALID),
                MESSAGE_ID(CHECK_DRIVER_MATCHING_IDENTIFIER_INVALID),
                MESSAGE_ID(CHECK_DRIVER_MATCHING_IDENTIFIER_DRIVER_REPORTED_ISSUE),
                MESSAGE_ID(RENDER_PASS_INVALID_RESOURCE_BARRIER),
                MESSAGE_ID(RENDER_PASS_DISALLOWED_API_CALLED),
                MESSAGE_ID(RENDER_PASS_CANNOT_NEST_RENDER_PASSES),
                MESSAGE_ID(RENDER_PASS_CANNOT_END_WITHOUT_BEGIN),
                MESSAGE_ID(RENDER_PASS_CANNOT_CLOSE_COMMAND_LIST),
                MESSAGE_ID(RENDER_PASS_GPU_WORK_WHILE_SUSPENDED),
                MESSAGE_ID(RENDER_PASS_MISMATCHING_SUSPEND_RESUME),
                MESSAGE_ID(RENDER_PASS_NO_PRIOR_SUSPEND_WITHIN_EXECUTECOMMANDLISTS),
                MESSAGE_ID(RENDER_PASS_NO_SUBSEQUENT_RESUME_WITHIN_EXECUTECOMMANDLISTS),
                MESSAGE_ID(TRACKED_WORKLOAD_COMMAND_QUEUE_MISMATCH),
                MESSAGE_ID(TRACKED_WORKLOAD_NOT_SUPPORTED),
                MESSAGE_ID(RENDER_PASS_MISMATCHING_NO_ACCESS),
                MESSAGE_ID(RENDER_PASS_UNSUPPORTED_RESOLVE),
                MESSAGE_ID(CLEARUNORDEREDACCESSVIEW_INVALID_RESOURCE_PTR),
                MESSAGE_ID(WINDOWS7_FENCE_OUTOFORDER_SIGNAL),
                MESSAGE_ID(WINDOWS7_FENCE_OUTOFORDER_WAIT),
                MESSAGE_ID(VIDEO_CREATE_MOTION_ESTIMATOR_INVALID_ARGUMENT),
                MESSAGE_ID(VIDEO_CREATE_MOTION_VECTOR_HEAP_INVALID_ARGUMENT),
                MESSAGE_ID(ESTIMATE_MOTION_INVALID_ARGUMENT),
                MESSAGE_ID(RESOLVE_MOTION_VECTOR_HEAP_INVALID_ARGUMENT),
                MESSAGE_ID(GETGPUVIRTUALADDRESS_INVALID_HEAP_TYPE),
                MESSAGE_ID(SET_BACKGROUND_PROCESSING_MODE_INVALID_ARGUMENT),
                MESSAGE_ID(CREATE_COMMAND_LIST_INVALID_COMMAND_LIST_TYPE_FOR_FEATURE_LEVEL),
                MESSAGE_ID(CREATE_VIDEOEXTENSIONCOMMAND),
                MESSAGE_ID(LIVE_VIDEOEXTENSIONCOMMAND),
                MESSAGE_ID(DESTROY_VIDEOEXTENSIONCOMMAND),
                MESSAGE_ID(INVALID_VIDEO_EXTENSION_COMMAND_ID),
                MESSAGE_ID(VIDEO_EXTENSION_COMMAND_INVALID_ARGUMENT),
                MESSAGE_ID(CREATE_ROOT_SIGNATURE_NOT_UNIQUE_IN_DXIL_LIBRARY),
                MESSAGE_ID(VARIABLE_SHADING_RATE_NOT_ALLOWED_WITH_TIR),
                MESSAGE_ID(GEOMETRY_SHADER_OUTPUTTING_BOTH_VIEWPORT_ARRAY_INDEX_AND_SHADING_RATE_NOT_SUPPORTED_ON_DEVICE),
                MESSAGE_ID(RSSETSHADING_RATE_INVALID_SHADING_RATE),
                MESSAGE_ID(RSSETSHADING_RATE_SHADING_RATE_NOT_PERMITTED_BY_CAP),
                MESSAGE_ID(RSSETSHADING_RATE_INVALID_COMBINER),
                MESSAGE_ID(RSSETSHADINGRATEIMAGE_REQUIRES_TIER_2),
                MESSAGE_ID(RSSETSHADINGRATE_REQUIRES_TIER_1),
                MESSAGE_ID(SHADING_RATE_IMAGE_INCORRECT_FORMAT),
                MESSAGE_ID(SHADING_RATE_IMAGE_INCORRECT_ARRAY_SIZE),
                MESSAGE_ID(SHADING_RATE_IMAGE_INCORRECT_MIP_LEVEL),
                MESSAGE_ID(SHADING_RATE_IMAGE_INCORRECT_SAMPLE_COUNT),
                MESSAGE_ID(SHADING_RATE_IMAGE_INCORRECT_SAMPLE_QUALITY),
                MESSAGE_ID(NON_RETAIL_SHADER_MODEL_WONT_VALIDATE),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_AS_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_MS_ROOT_SIGNATURE_MISMATCH),
                MESSAGE_ID(ADD_TO_STATE_OBJECT_ERROR),
                MESSAGE_ID(CREATE_PROTECTED_RESOURCE_SESSION_INVALID_ARGUMENT),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_MS_PSO_DESC_MISMATCH),
                MESSAGE_ID(CREATEPIPELINESTATE_MS_INCOMPLETE_TYPE),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_AS_NOT_MS_MISMATCH),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_MS_NOT_PS_MISMATCH),
                MESSAGE_ID(NONZERO_SAMPLER_FEEDBACK_MIP_REGION_WITH_INCOMPATIBLE_FORMAT),
                MESSAGE_ID(CREATEGRAPHICSPIPELINESTATE_INPUTLAYOUT_SHADER_MISMATCH),
                MESSAGE_ID(EMPTY_DISPATCH),
                MESSAGE_ID(RESOURCE_FORMAT_REQUIRES_SAMPLER_FEEDBACK_CAPABILITY),
                MESSAGE_ID(SAMPLER_FEEDBACK_MAP_INVALID_MIP_REGION),
                MESSAGE_ID(SAMPLER_FEEDBACK_MAP_INVALID_DIMENSION),
                MESSAGE_ID(SAMPLER_FEEDBACK_MAP_INVALID_SAMPLE_COUNT),
                MESSAGE_ID(SAMPLER_FEEDBACK_MAP_INVALID_SAMPLE_QUALITY),
                MESSAGE_ID(SAMPLER_FEEDBACK_MAP_INVALID_LAYOUT),
                MESSAGE_ID(SAMPLER_FEEDBACK_MAP_REQUIRES_UNORDERED_ACCESS_FLAG),
                MESSAGE_ID(SAMPLER_FEEDBACK_CREATE_UAV_NULL_ARGUMENTS),
                MESSAGE_ID(SAMPLER_FEEDBACK_UAV_REQUIRES_SAMPLER_FEEDBACK_CAPABILITY),
                MESSAGE_ID(SAMPLER_FEEDBACK_CREATE_UAV_REQUIRES_FEEDBACK_MAP_FORMAT),
                MESSAGE_ID(CREATEMESHSHADER_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATEMESHSHADER_OUTOFMEMORY),
                MESSAGE_ID(CREATEMESHSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE),
                MESSAGE_ID(RESOLVESUBRESOURCE_SAMPLER_FEEDBACK_TRANSCODE_INVALID_FORMAT),
                MESSAGE_ID(RESOLVESUBRESOURCE_SAMPLER_FEEDBACK_INVALID_MIP_LEVEL_COUNT),
                MESSAGE_ID(RESOLVESUBRESOURCE_SAMPLER_FEEDBACK_TRANSCODE_ARRAY_SIZE_MISMATCH),
                MESSAGE_ID(SAMPLER_FEEDBACK_CREATE_UAV_MISMATCHING_TARGETED_RESOURCE),
                MESSAGE_ID(CREATEMESHSHADER_OUTPUTEXCEEDSMAXSIZE),
                MESSAGE_ID(CREATEMESHSHADER_GROUPSHAREDEXCEEDSMAXSIZE),
                MESSAGE_ID(VERTEX_SHADER_OUTPUTTING_BOTH_VIEWPORT_ARRAY_INDEX_AND_SHADING_RATE_NOT_SUPPORTED_ON_DEVICE),
                MESSAGE_ID(MESH_SHADER_OUTPUTTING_BOTH_VIEWPORT_ARRAY_INDEX_AND_SHADING_RATE_NOT_SUPPORTED_ON_DEVICE),
                MESSAGE_ID(CREATEMESHSHADER_MISMATCHEDASMSPAYLOADSIZE),
                MESSAGE_ID(CREATE_ROOT_SIGNATURE_UNBOUNDED_STATIC_DESCRIPTORS),
                MESSAGE_ID(CREATEAMPLIFICATIONSHADER_INVALIDSHADERBYTECODE),
                MESSAGE_ID(CREATEAMPLIFICATIONSHADER_OUTOFMEMORY),
                MESSAGE_ID(CREATE_SHADERCACHESESSION),
                MESSAGE_ID(LIVE_SHADERCACHESESSION),
                MESSAGE_ID(DESTROY_SHADERCACHESESSION),
                MESSAGE_ID(CREATESHADERCACHESESSION_INVALIDARGS),
                MESSAGE_ID(CREATESHADERCACHESESSION_DISABLED),
                MESSAGE_ID(CREATESHADERCACHESESSION_ALREADYOPEN),
                MESSAGE_ID(SHADERCACHECONTROL_DEVELOPERMODE),
                MESSAGE_ID(SHADERCACHECONTROL_INVALIDFLAGS),
                MESSAGE_ID(SHADERCACHECONTROL_STATEALREADYSET),
                MESSAGE_ID(SHADERCACHECONTROL_IGNOREDFLAG),
                MESSAGE_ID(SHADERCACHESESSION_STOREVALUE_ALREADYPRESENT),
                MESSAGE_ID(SHADERCACHESESSION_STOREVALUE_HASHCOLLISION),
                MESSAGE_ID(SHADERCACHESESSION_STOREVALUE_CACHEFULL),
                MESSAGE_ID(SHADERCACHESESSION_FINDVALUE_NOTFOUND),
                MESSAGE_ID(SHADERCACHESESSION_CORRUPT),
                MESSAGE_ID(SHADERCACHESESSION_DISABLED),
                MESSAGE_ID(OVERSIZED_DISPATCH),
                MESSAGE_ID(CREATE_VIDEOENCODER),
                MESSAGE_ID(LIVE_VIDEOENCODER),
                MESSAGE_ID(DESTROY_VIDEOENCODER),
                MESSAGE_ID(CREATE_VIDEOENCODERHEAP),
                MESSAGE_ID(LIVE_VIDEOENCODERHEAP),
                MESSAGE_ID(DESTROY_VIDEOENCODERHEAP),
                MESSAGE_ID(COPYTEXTUREREGION_MISMATCH_ENCODE_REFERENCE_ONLY_FLAG),
                MESSAGE_ID(COPYRESOURCE_MISMATCH_ENCODE_REFERENCE_ONLY_FLAG),
                MESSAGE_ID(ENCODE_FRAME_INVALID_PARAMETERS),
                MESSAGE_ID(ENCODE_FRAME_UNSUPPORTED_PARAMETERS),
                MESSAGE_ID(RESOLVE_ENCODER_OUTPUT_METADATA_INVALID_PARAMETERS),
                MESSAGE_ID(RESOLVE_ENCODER_OUTPUT_METADATA_UNSUPPORTED_PARAMETERS),
                MESSAGE_ID(CREATE_VIDEO_ENCODER_INVALID_PARAMETERS),
                MESSAGE_ID(CREATE_VIDEO_ENCODER_UNSUPPORTED_PARAMETERS),
                MESSAGE_ID(CREATE_VIDEO_ENCODER_HEAP_INVALID_PARAMETERS),
                MESSAGE_ID(CREATE_VIDEO_ENCODER_HEAP_UNSUPPORTED_PARAMETERS),
                MESSAGE_ID(CREATECOMMANDLIST_NULL_COMMANDALLOCATOR),
                MESSAGE_ID(CLEAR_UNORDERED_ACCESS_VIEW_INVALID_DESCRIPTOR_HANDLE),
                MESSAGE_ID(DESCRIPTOR_HEAP_NOT_SHADER_VISIBLE),
                MESSAGE_ID(CREATEBLENDSTATE_BLENDOP_WARNING),
                MESSAGE_ID(CREATEBLENDSTATE_BLENDOPALPHA_WARNING),
                MESSAGE_ID(WRITE_COMBINE_PERFORMANCE_WARNING),
                MESSAGE_ID(RESOLVE_QUERY_INVALID_QUERY_STATE),
                MESSAGE_ID(SETPRIVATEDATA_NO_ACCESS),
                MESSAGE_ID(D3D12_MESSAGES_END)
            };

            /// <summary>
            /// Describes the level of GPU-based validation to perform at runtime.
            /// </summary>
            [Flags]
            public enum class D3D12GPUBasedValidationFlags : UINT
            {
                /// <summary>
                /// Default behavior; resource states, descriptors, and descriptor tables are all
                /// validated.
                /// </summary>
                None = D3D12_GPU_BASED_VALIDATION_FLAGS_NONE,

                /// <summary>
                /// When set, GPU-based validation does not perform resource state validation which
                /// greatly reduces the performance cost of GPU-based validation. Descriptors and
                /// descriptor heaps are still validated.
                /// </summary>
                DisableStateTracking = D3D12_GPU_BASED_VALIDATION_FLAGS_DISABLE_STATE_TRACKING
            };

            /// <summary>
            /// Indicates the debug parameter type used by D3D12DebugCommandList1::SetDebugParameter and
            /// D3D12DebugCommandList1::GetDebugParameter.
            /// </summary>
            public enum class D3D12DebugCommandListParameterType : UINT
            {
                /// <summary>
                /// Indicates the parameter is type D3D12DebugCommandListGPUBasedValidationSettings.
                /// </summary>
                GPUBasedValidationSettings = D3D12_DEBUG_COMMAND_LIST_PARAMETER_GPU_BASED_VALIDATION_SETTINGS
            };

            /// <summary>
            /// Specifies the type of shader patching used by GPU-Based Validation at either the device
            /// or command list level.
            /// </summary>
            public enum class D3D12GPUBasedValidationShaderPatchMode : UINT
            {
                /// <summary>
                /// No shader patching is to be done. This will retain the original shader bytecode.
                /// Can lead to errors in some of the GPU-Based Validation state tracking as the
                /// unpatched shader may still change resource state but the promotion will be untracked
                /// without patching the shader. This can improve performance but no validation will be
                /// performed and may also lead to misleading GPU-Based Validation errors. Use this mode
                /// very carefully.
                /// </summary>
                None = D3D12_GPU_BASED_VALIDATION_SHADER_PATCH_MODE_NONE,

                /// <summary>
                /// Shaders can be patched with resource state tracking code but no validation. This
                /// may improve performance but no validation will be performed.
                /// </summary>
                StateTrackingOnly = D3D12_GPU_BASED_VALIDATION_SHADER_PATCH_MODE_STATE_TRACKING_ONLY,

                /// <summary>
                /// The default. Shaders are patched with validation code but erroneous instructions
                /// will still be executed.
                /// </summary>
                UnguardedValidation = D3D12_GPU_BASED_VALIDATION_SHADER_PATCH_MODE_UNGUARDED_VALIDATION,

                /// <summary>
                /// Shaders are patched with validation code and erroneous instructions are skipped in
                /// execution. This can help avoid crashes or device removal.
                /// </summary>
                GuardedValidation = D3D12_GPU_BASED_VALIDATION_SHADER_PATCH_MODE_GUARDED_VALIDATION,

                /// <summary>
                /// Unused, simply the count of the number of modes.
                /// </summary>
                NumPatchModes = NUM_D3D12_GPU_BASED_VALIDATION_SHADER_PATCH_MODES
            };

            /// <summary>
            /// Specifies the data type of the memory pointed to by the data parameter of
            /// D3D12DebugDevice1::SetDebugParameter and D3D12DebugDevice1::GetDebugParameter.
            /// </summary>
            public enum class D3D12DebugDeviceParameterType : UINT
            {
                /// <summary>
                /// Indicates data points to a D3D12DebugDeviceFeatureFlags structure.
                /// </summary>
                FeatureFlags = D3D12_DEBUG_DEVICE_PARAMETER_FEATURE_FLAGS,

                /// <summary>
                /// Indicates data points to a D3D12DebugDeviceGPUBasedValidationSettings structure.
                /// </summary>
                GPUBasedValidationSettings = D3D12_DEBUG_DEVICE_PARAMETER_GPU_BASED_VALIDATION_SETTINGS,

                /// <summary>
                /// Indicates data points to a D3D12DebugDeviceGPUSlowdownPerformanceFactor structure.
                /// </summary>
                GPUSlowdownPerformanceFactor = D3D12_DEBUG_DEVICE_PARAMETER_GPU_SLOWDOWN_PERFORMANCE_FACTOR
            };

            /// <summary>
            /// Specifies how GPU-Based Validation handles patched pipeline states during
            /// D3D12Device::CreateGraphicsPipelineState and D3D12Device::CreateComputePipelineState.
            /// </summary>
            [Flags]
            public enum class D3D12GPUBasedValidationPipelineStateCreateFlags : UINT
            {
                /// <summary>
                /// This is the default value. Indicates no patching of pipeline states should be done
                /// during PSO creation. Instead PSO¡¯s are patched on first use in a command list. This
                /// can help to reduce the up-front cost of PSO creation but may instead slow down
                /// command list recording until a steady-state is reached.
                /// </summary>
                None = D3D12_GPU_BASED_VALIDATION_PIPELINE_STATE_CREATE_FLAG_NONE,

                /// <summary>
                /// Indicates that state-tracking GPU-Based Validation PSO¡¯s should be created along
                /// with the original PSO at create time.
                /// </summary>
                FrontLoadCreateTrackingOnlyShaders = D3D12_GPU_BASED_VALIDATION_PIPELINE_STATE_CREATE_FLAG_FRONT_LOAD_CREATE_TRACKING_ONLY_SHADERS,

                /// <summary>
                /// Indicates that unguarded GPU-Based Validation PSO¡¯s should be created along with
                /// the original PSO at create time.
                /// </summary>
                FrontLoadCreateUnguardedValidationShaders = D3D12_GPU_BASED_VALIDATION_PIPELINE_STATE_CREATE_FLAG_FRONT_LOAD_CREATE_UNGUARDED_VALIDATION_SHADERS,

                /// <summary>
                /// Indicates that guarded GPU-Based Validation PSO¡¯s should be created along with
                /// the original PSO at create time.
                /// </summary>
                FrontLoadCreateGuardedValidationShaders = D3D12_GPU_BASED_VALIDATION_PIPELINE_STATE_CREATE_FLAG_FRONT_LOAD_CREATE_GUARDED_VALIDATION_SHADERS,

                /// <summary>
                /// Internal use only.
                /// </summary>
                ValidMask = D3D12_GPU_BASED_VALIDATION_PIPELINE_STATE_CREATE_FLAGS_VALID_MASK
            };

            /// <summary>
            /// Specifies the flags for message callbacks.
            /// </summary>
            [Flags]
            public enum class D3D12MessageCallbackFlags : UINT
            {
                /// <summary>
                /// Callback is filtered in the exact same way as what gets logged as debug text.
                /// </summary>
                None = D3D12_MESSAGE_CALLBACK_FLAG_NONE,

                /// <summary>
                /// Callback is unfiltered.
                /// </summary>
                IgnoreFilters = D3D12_MESSAGE_CALLBACK_IGNORE_FILTERS
            };

            /// <summary>
            /// Callback for debug messages used in D3D12InfoQueue1.
            /// </summary>
            /// <param name="category">Category of the debug message produced.</param>
            /// <param name="severity">Severity of the debug message produced.</param>
            /// <param name="id">ID of the debug message produced.</param>
            /// <param name="description">Debug message description.</param>
            /// <param name="pContext">Pointer to user-supplied data that will be passed into each
            /// callback invocation. The memory pointed to by pContext must remain valid until the
            /// callback has been unregistered.</param>
            [UnmanagedFunctionPointer(CallingConvention::StdCall)]
            public delegate void D3D12MessageCallback(
                D3D12MessageCategory category,
                D3D12MessageSeverity severity,
                D3D12MessageID id,
                String^ description,
                void* pContext
            );
            


            /// <summary>
            /// Indicates the struct is the debug parameter used in D3D12DebugCommandList1.
            /// </summary>
            public interface class ICommandListDebugParameter
            {
                /// <summary>
                /// Gets the type of the parameter.
                /// </summary>
                property D3D12DebugCommandListParameterType ParameterType
                {
                    D3D12DebugCommandListParameterType get();
                }
            };

            /// <summary>
            /// Indicates the struct is the debug parameter used in D3D12DebugDevice1.
            /// </summary>
            public interface class IDeviceDebugParameter
            {
                /// <summary>
                /// Gets the type of the parameter.
                /// </summary>
                property D3D12DebugDeviceParameterType ParameterType
                {
                    D3D12DebugDeviceParameterType get();
                }
            };

            /// <summary>
            /// A debug message in the Information Queue.
            /// </summary>
            public value struct D3D12Message
            {
                /// <summary>
                /// The category of the message.
                /// </summary>
                D3D12MessageCategory Category;

                /// <summary>
                /// The severity of the message. 
                /// </summary>
                D3D12MessageSeverity Severity;

                /// <summary>
                /// The ID of the message.
                /// </summary>
                D3D12MessageID ID;

                /// <summary>
                /// The message string.
                /// </summary>
                String^ Description;
            };

            /// <summary>
            /// Allow or deny certain types of messages to pass through a filter.
            /// </summary>
            public value struct D3D12InfoQueueFilterDesc
            {
                /// <summary>
                /// Array of message categories to allow or deny.
                /// </summary>
                array<D3D12MessageCategory>^ CategoryList;

                /// <summary>
                /// Array of message severity levels to allow or deny.
                /// </summary>
                array<D3D12MessageSeverity>^ SeverityList;

                /// <summary>
                /// Array of message IDs to allow or deny.
                /// </summary>
                array<D3D12MessageID>^ IDList;
            };

            /// <summary>
            /// Debug message filter; contains a lists of message types to allow or deny.
            /// </summary>
            public value struct D3D12InfoQueueFilter
            {
                /// <summary>
                /// Specifies types of messages that you want to allow.
                /// </summary>
                D3D12InfoQueueFilterDesc AllowList;

                /// <summary>
                /// Specifies types of messages that you want to deny.
                /// </summary>
                D3D12InfoQueueFilterDesc DenyList;
            };

            /// <summary>
            /// Describes per-command-list settings used by GPU-Based Validation.
            /// </summary>
            [StructLayout(LayoutKind::Sequential)]
            public value struct D3D12DebugCommandListGPUBasedValidationSettings : ICommandListDebugParameter
            {
                /// <summary>
                /// Specifies a D3D12GPUBasedValidationShaderPatchMode that overrides the default
                /// device-level shader patch mode. By default this value is initialized to the
                /// DefaultShaderPatchMode assigned to the device.
                /// </summary>
                D3D12GPUBasedValidationShaderPatchMode ShaderPatchMode;

                virtual property D3D12DebugCommandListParameterType ParameterType
                {
                    virtual D3D12DebugCommandListParameterType get()
                    {
                        return D3D12DebugCommandListParameterType::GPUBasedValidationSettings;
                    }
                }
            };

            /// <summary>
            /// Describes flags for optional D3D12 Debug Layer features.
            /// </summary>
            [StructLayout(LayoutKind::Sequential)]
            public value struct D3D12DebugDeviceFeatureFlags : IDeviceDebugParameter
            {
                /// <summary>
                /// Flags for optional D3D12 Debug Layer features.
                /// </summary>
                D3D12DebugFeature Flags;

                virtual property D3D12DebugDeviceParameterType ParameterType
                {
                    virtual D3D12DebugDeviceParameterType get()
                    {
                        return D3D12DebugDeviceParameterType::FeatureFlags;
                    }
                }
            };

            /// <summary>
            /// Describes settings used by GPU-Based Validation.
            /// </summary>
            [StructLayout(LayoutKind::Sequential)]
            public value struct D3D12DebugDeviceGPUBasedValidationSettings : IDeviceDebugParameter
            {
                /// <summary>
                /// Specifies a UINT that limits the number of messages that can be stored in the
                /// GPU-Based Validation message log. The default value is 256. Since many identical
                /// errors can be produced in a single Draw/Dispatch call it may be useful to increase
                /// this number. Note this can become a memory burden if a large number of command lists
                /// are used as there is a committed message log per command list.
                /// </summary>
                unsigned int MaxMessagesPerCommandList;

                /// <summary>
                /// Specifies the D3D12GPUBasedValidationShaderPatchMode that GPU-Based Validation uses
                /// when injecting validation code into shaders, except when overridden by
                /// per-command-list GPU-Based Validation settings. The default value is
                /// D3D12GPUBasedValidationShaderPatchMode::UnguardedValidation.
                /// </summary>
                D3D12GPUBasedValidationShaderPatchMode DefaultShaderPatchMode;

                /// <summary>
                /// Specifies one of the D3D12GPUBasedValidationPipelineStateCreateFlags that
                /// indicates how GPU-Based Validation handles patching pipeline states. The default
                /// value is D3D12GPUBasedValidationPipelineStateCreateFlags::None.
                /// </summary>
                D3D12GPUBasedValidationPipelineStateCreateFlags PipelineStateCreateFlags;

                virtual property D3D12DebugDeviceParameterType ParameterType
                {
                    virtual D3D12DebugDeviceParameterType get()
                    {
                        return D3D12DebugDeviceParameterType::GPUBasedValidationSettings;
                    }
                }
            };

            /// <summary>
            /// Describes the amount of artificial slowdown inserted by the debug device to simulate
            /// lower-performance graphics adapters.
            /// </summary>
            [StructLayout(LayoutKind::Sequential)]
            public value struct D3D12DebugDeviceGPUSlowdownPerformanceFactor
            {
                /// <summary>
                /// Specifies the amount of slowdown artificially applied, as a factor of the nominal
                /// time for the fence to signal. The default value is 0.
                /// </summary>
                float SlowdownFactor;

                virtual property D3D12DebugDeviceParameterType ParameterType
                {
                    virtual D3D12DebugDeviceParameterType get()
                    {
                        return D3D12DebugDeviceParameterType::GPUSlowdownPerformanceFactor;
                    }
                }
            };
        }
    }
}